### ISSUE TITLE
update/upgrade vs just update salt on Debian?

### ISSUE THREAD

**Issue by WilCrofter** [alexander-bauer/caf-1222-salt#10]
Re: # Install up-to-date Salt package repositories on non-Arch minions.

Wondering if, as for Arch, full system upgrades rather than single package upgrades are desirable.

For Arch, automated full system upgrades  are complicated by occasional special directives which appear on (Arch latest news)[https://www.archlinux.org/]. 

For Debian 'apt-get upgrade -y' does not suppress occasional invocations of a system editor to present well intentioned, if generally unintelligible, information about new package versions. 'apt-get upgrade -qq' may suppress such invocation. I'm not sure.

**Comment by alexander-bauer** [comment]
Interestingly, [Arch doesn't support partial upgrades](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported). That is, you never want to run `pacman -Sy salt`. However, you can run `pacman -S salt` just fine -- so long as you don't update from the repositories without upgrading everything.

The latest version of Salt installed for all of the Arch boxes should be fine -- the trouble I was having on #5 was that the server (an Ubuntu 16.10 instance) was incompatible with the newer clients. Since I started using `salt-formula` (#4), any non-Arch clients will get the Salt package repositories installed, so they can receive new versions.

**Comment by WilCrofter** [comment]
As I understand it then, installation of individual packages without full system upgrades should not be a problem for either Debian or Arch?

**Comment by alexander-bauer** [comment]
That's right -- so long as the package installation on Arch doesn't require syncing from the repositories. It probably won't be an issue.

**Comment by WilCrofter** [comment]
Thank you. Closing the issue.
