### ISSUE TITLE
Question on updating gitfs_remotes

### ISSUE THREAD

**Issue by WilCrofter** [alexander-bauer/caf-1222-salt#11]
Re: [Updating gitfs_remotes](https://github.com/alexander-bauer/caf-1222-salt#updating-gitfs_remotes) specifically, "new states will not be available until the master rule is applied and it is restarted."

The following two commands are presumably executed on an affected minion. Does the first apply the master rule to the minion? What does "it" refer to in the above quote, the salt-minion service?

```
salt-call state.apply salt.master
salt-call state.apply
```

**Comment by alexander-bauer** [comment]
This is a bit confusing, because I wrote it thinking only of services which happen to also run on the salt master. The first command must be run on the master (because it updates the master config file and restarts the service), and the second must be run on the affected minion.

The reason for this is that the new `gitfs_remote` provides states which the minion will now rely on. These must be provided by the master, but if the master doesn't have its rules applied, then they will not be loaded into the master config. If the master is also the affected minion, then you have to apply the `salt.master` state explicitly, because otherwise the apply will fail, for not yet being able to find the new state.

**Comment by WilCrofter** [comment]
OK. I will do that post haste, initially by pasting your answer into the README, and cleaning it up as time permits. Closing issue.
